Models conversion and related tests for smooth loading into drake
EricCousineau-TRI/repro pull request #73
Opened 2021-10-29 10:20 UTC by marcoag

This PR is to provide a point of discussion and follow up on the issue https://github.com/RobotLocomotion/drake/issues/15024.

It adds [IoU](https://en.wikipedia.org/wiki/Jaccard_index) testing to the model transformation process. It does this for default joint poses and random joint poses:

- It creates a temp directory to store all the temporal stuff that will be created. It's name is printed at the begging of the script output.
- It downloads and compiles the [ModelPhotoShoot gazebo plugin](https://github.com/marcoag/ModelPhotoShoot).
- It loads the model in gazebo and makes the required pictures using the previous plugin.
- It runs the `test_models.py` script which will load the model in drake and take the same pictures. This script will also produce the IoU results and other tests using drake.

To run the entire process (all the above plus the model conversion):

./setup.sh <model_directory> <file_modelname.sdf> 

For an easier debug process I created a jupyter notebook ([Model_photo_testing.ipynb](https://github.com/marcoag/repro/blob/focal_robot_cameras_issue/drake_stuff/mbp_robot_arm_joint_limit_stuff/Model_photo_testing.ipynb)), note that this code does not perform the model conversion nor the plugin download and compilation so those steps would have to be done previously. Also the variables at the top related to certain files locations might have to be adjusted.

This has been tested with the following models:

- [shadow_hand](https://app.ignitionrobotics.org/AndrejOrsula/fuel/models/shadow_hand)
- [ur5_rg2](https://app.ignitionrobotics.org/AndrejOrsula/fuel/models/ur5_rg2)
- [Panda with Ignition position controller model](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/Panda%20with%20Ignition%20position%20controller%20model)
- [CERBERUS_ANYMAL_C_SENSOR_CONFIG_2](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2)
- [NAO with Ignition position controller](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/NAO%20with%20Ignition%20position%20controller)
- [MPL right arm](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/MPL%20right%20arm)

Pending issues:

1. [x] The gazebo plugin seems to have problems loading the `MPL right arm` model. (fixed in https://github.com/EricCousineau-TRI/repro/pull/73/commits/8130ffb0b1e21c4ebd87c2455d48fdbf6af24c0f)
2. [x] The robot on the drake pictures look bigger when the robot is big and smaller when the robot is small, even when the intrinsic are set to the same values.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ericcousineau-tri/repro/73)

2021-11-01 14:26 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MnQt-vz5FSoDuqgpp9R:br5alhk) (no related file):*
Working: Will run locally, see if I can repro rendering diff. for NAO / ANYMal, and see if we can distill to simpler example as in this notebook:
https://github.com/EricCousineau-TRI/repro/blob/master/drake_stuff/notebooks/sphere_rendering.ipynb

---


<!-- Sent from Reviewable.io -->

2021-11-04 19:36 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MngRP3-EFM6RIts50cm:bgjfwp0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Will run locally, see if I can repro rendering diff. for NAO / ANYMal, and see if we can distill to simpler example as in this notebook:
https://github.com/EricCousineau-TRI/repro/blob/master/drake_stuff/notebooks/sphere_rendering.ipynb
</blockquote></details>

Which Gazebo should I use? I'm assuming Ignition Gazebo, Fortress?

---


<!-- Sent from Reviewable.io -->

2021-11-04 19:43 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MngTVBi-8HEwn81KRvv:b-4jvqon) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Which Gazebo should I use? I'm assuming Ignition Gazebo, Fortress?
</blockquote></details>

Ohh, I don't see any env vars for Ignition Gazebo; so perhaps it should be Gazebo classic?

---


<!-- Sent from Reviewable.io -->

2021-11-05 00:51 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MnhZs7A4sHqucVobjK7:b3tcf4h) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ohh, I don't see any env vars for Ignition Gazebo; so perhaps it should be Gazebo classic?
</blockquote></details>

Correct, Gazebo classic.

---


<!-- Sent from Reviewable.io -->

2021-11-05 14:28 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MnkUuM68n5fij5PAgWX:bd073pr) (no related file):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Correct, Gazebo classic.
</blockquote></details>

Can I ask what the motivation was for Gazebo classic (older versions of `libsdformat`) vs. Ignition Gazebo?

Is it difficult to remap this onto Ignition Gazebo? (perhaps not immediately, but say in a few weeks?)

---


<!-- Sent from Reviewable.io -->

2021-11-05 14:37 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 165 at r1](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnkWRP83i9GpCJZqE6t:-MnkWRP83i9GpCJZqE6u:bvphdyt) ([raw file](https://github.com/ericcousineau-tri/repro/blob/fd357cd63d5569450301c12dabc6183ff6de3cc4/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L165)):*
> ```Shell
> fi
> 
> temp_directory=$(mktemp -d)
> ```

Working: This should source Gazebo setup file too.


<!-- Sent from Reviewable.io -->

2021-11-08 07:00 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-MnyDLn-B9N6prc5PQ1M:b-u1adum) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can I ask what the motivation was for Gazebo classic (older versions of `libsdformat`) vs. Ignition Gazebo?

Is it difficult to remap this onto Ignition Gazebo? (perhaps not immediately, but say in a few weeks?)
</blockquote></details>

The reason to go for gazebo classic was the existence of the ModelProShop plugin: https://github.com/osrf/gazebo/blob/gazebo11/plugins/ModelPropShop.cc, which was used to take different images for fuel. I am not aware of the existence of a similar plugin for Ignition Gazebo but I guess worst case scenario we can port it... 

---


<!-- Sent from Reviewable.io -->

2021-11-15 01:47 UTC, EricCousineau-TRI commented
It took me a bit to figure out exact correct invocation for stuff like Cerberus.

I'm trying to patch this PR w/ exact instructions, but I'm having trouble with using `wget`, `curl`, or `ign fuel` to download the archive.
Things I've tried for https://app.ignitionrobotics.org/OpenRobotics/fuel/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2/6
```
# Download the archive from browser, extract download link, and test with wget or curl.
$ wget <url> -O model.zip
# Only has HTML information
$ curl <url> -o model.zip
# Only has HTML information

# Try using `ign fuel`
$ ign fuel download --url https://app.ignitionrobotics.org/OpenRobotics/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2/6
[Err] [FuelClient.cc:571] Can't download model, server configuration incomplete:
...
```

Is there something I'm missing here?

2021-11-15 01:53 UTC, EricCousineau-TRI commented
Pushed manual steps for now in 8090178

2021-11-15 14:28 UTC, marcoag reviewed
It seems the ignition website is using blobs to generate the download link for the model, so I used the browser developer tools to figure out the actual location of the file, this one works for me:

`$ wget https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2/6/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2.zip`

Using ignition fuel I use the url from the bibtex at the bottom of the page:

`$  ign fuel download --url https://app.ignitionrobotics.org/OpenRobotics/fuel/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2`

this leaves the downloaded model at ~/.ignition/fuel/fuel.ignitionrobotics.org/openrobotics/models/

> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-:-MoYxYKX7y5Ho0K7ZA_S:bszy0aq)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2021-11-15 14:47 UTC, EricCousineau-TRI commented
Ah, gotcha! I can run the `wget` command. Is it easy to expose this in the Ignition Fuel website? (or should we simply file an issue?)

Regarding `ign fuel`, I am unable to download it w/ above command:
```
$ ign fuel download --url https://app.ignitionrobotics.org/OpenRobotics/fuel/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2
Invalid URL: only models and worlds or collections can be downloaded so far.
```
Version:
```
$ dpkg -s ignition-tools | grep Version
Version: 1.4.1-1~focal
```

2021-11-15 15:00 UTC, marcoag reviewed
It's not hard to figure out but you have to use the developer tools. Usually the usage of blobs for file downloads is intentional to hide the actual location of the file, so I am not sure how much the ignition team will be willing to expose this URL further. 

Sorry about that, I posted the wrong  URL, this one should work (it's the URL from the BibTeX at the bottom of the page of the model):

`ign fuel download --url https://fuel.ignitionrobotics.org/1.0/OpenRobotics/models/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2`

> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-:-MoZ4y3y9bYdvjyvqh8N:bcjeevw)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2021-11-15 15:31 UTC, EricCousineau-TRI commented
Per VC, perhaps use Ignition Gazebo + this GSoC plugin?
https://community.gazebosim.org/t/gsoc-2021-machine-learning-extension-to-ignition-gazebo/1070

2022-03-02 16:39 UTC, marcoag commented
Latest changes move the camera instead of the model to center and scale the model to fit the image. It also contains some fixes and workarounds to make the tests work for visual and collision meshes with the joints in default and random positions. 

There's an issue that manifests with the model [MPL right arm](https://app.ignitionrobotics.org/OpenRobotics/fuel/models/MPL%20right%20arm) that would make `drake` ignore the `<pose>` in the first `<link>`, this is, the offset between the model and the world. This happens when loading the model and then welding it without providing the `X_PC` rigid transform. Since `drake` will use a default identity matrix for this, no offset will be applied between the world and the model, leaving the model fixed at the origin and ignoring whatever offset it might have had in that initial `<pose>`. Maybe the cleaner solution would be to provide that offset on the `X_PC` parameter, but I can't seem to retrieve that `<pose>` value at the `drake` level since most of the introspection methods require the plant to be finalized. The current workaround that was implemented adds a fixed `joint` to the world at the `sdf` level, this makes `drake` load the model welded with the correct offset (no further welding is done after loading). Since not having this fixed joint in the `sdf` would make hard to load the model in the correct position in `drake`, it gets currently added to the final output `sdf` that the user would get as a result of the model transformation process, let me know if we should do otherwise.

2022-03-03 02:11 UTC, EricCousineau-TRI commented
Sounds good! My request is to try to retrieve the pose programmatically, using `{Get,Set}DefaultFreeBodyPose`.

I think you could do something like:
```
canonical_link = plant.GetFrameByName("__model__", my_model).body()
X_WL = plant.GetDefaultFreeBodyPose(canonical_link)
# use offset to weld
```

Can you give this a whirl?

2022-03-03 03:49 UTC, marcoag commented
Yup, that seems to be exactly what i was missing. Thanks! I added it to the model loading process and removed the part that was adding the fixed joint.

2022-03-07 15:15 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-MxZwcgW8XNgASfIXVdC:bm3ka0m) (no related file):*
Working: Should determine best place for this to land, e..g `drake-ignitino`, `drake-model-interop`, `drake-compatibility`, `drake-comparison`, `drake-benchmarks`.

Once we have some candidates, should post to Drake Slack to solicit other Drake Dev opinions.

---


<!-- Sent from Reviewable.io -->

2022-03-07 16:02 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 8 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnQt-vx7w1pThJSjB62:-Mx_4eac6P_CbiWzDN-H:b-agf280) (no related file):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

The reason to go for gazebo classic was the existence of the ModelProShop plugin: https://github.com/osrf/gazebo/blob/gazebo11/plugins/ModelPropShop.cc, which was used to take different images for fuel. I am not aware of the existence of a similar plugin for Ignition Gazebo but I guess worst case scenario we can port it... 
</blockquote></details>

OK Marking as resolved given ignition efforts - thanks!

---
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 5 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_54FI5y-Cn2D6bd04:-Mx_54FI5y-Cn2D6bd05:b-oeceh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L5)):*
> ```Markdown
> ## Prereqs
> 
> Tested on Ubuntu 20.04 (Focal).
> ```

How much do we need ROS 1? Is it possible to make this all work with just `xacro`?

(or does `roslaunch` basically tie our hands?)
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 7 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_4tAfB867imO4VfQQ:-Mx_4tAfB867imO4VfQR:bf5p6rz) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L7)):*
> ```Markdown
> Tested on Ubuntu 20.04 (Focal).
> 
> - Install Gazebo Classic:
> ```

Is this still true? (should this be ignition?)
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 27 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_60TQ-OrZP9wgg8uu:-Mx_60TQ-OrZP9wgg8uv:bawfom8) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L27)):*
> ```Markdown
> unzip /tmp/CERBERUS_ANYMAL_C_SENSOR_CONFIG_2.zip -d ./CERBERUS_ANYMAL_C_SENSOR_CONFIG_2/
> 
> # Run setup.
> ```

Is it possible to split up general setup (virtualenv, drake, etc) and per-model testing into separate scripts? e.g.
```
./setup.sh

mkdir -p repos && cd repos
# untar stuff
./format_model_and_generate_manifest.py ... model.sdf
./compare_model_via_drake_and_ingitiom_images.py ...

```
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 14 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_56uUB9ZRmHHf8MM9:-Mx_56uUB9ZRmHHf8MMA:b-ljpgpq) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L14)):*
> ```Python
> from os.path import abspath, dirname, isfile
> from subprocess import PIPE, run
> import sys
> ```

For Python styling, could you use `black`?
https://github.com/psf/black
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 117 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5Je_6F27LGjJnvpe:-Mx_5Je_6F27LGjJnvpf:b-3p6jsv) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L117)):*
> ```Python
> 
>   # Workaround for issue https: // github.com/assimp/assimp/issues/849.
>   if(suffix == ".dae"):
> ```

nit Can you carve this into a separate function?
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-Mx_5f345IKkcQ6jxnMQ:b-mhietu) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
> ```Shell
> ) }
> 
> _generate_sdf() { (
> ```

Yeah, can you carve out all complex instructions / tests into a Python file?
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py, line 213 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5VJ4DdJjIqdSqPa2:-Mx_5VJ4DdJjIqdSqPa3:b-ighotz) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L213)):*
> ```Python
> if __name__ == "__main__":
>   try:
>     main(sys.argv[1], sys.argv[2], sys.argv[3])
> ```

nit Relying on raw `argv` for simple cases may be confusing.

Can you use `argparse` here?


<!-- Sent from Reviewable.io -->

2022-03-28 07:32 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 5 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_54FI5y-Cn2D6bd04:-MyqOvZeABC3RIuPU4iE:b-sq5mmw) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L5)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

How much do we need ROS 1? Is it possible to make this all work with just `xacro`?

(or does `roslaunch` basically tie our hands?)
</blockquote></details>

I believe `roslaunch` does tie our hands here.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 7 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_4tAfB867imO4VfQQ:-MygBm5QDvUt60fBo07r:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is this still true? (should this be ignition?)
</blockquote></details>

Done.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 27 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_60TQ-OrZP9wgg8uu:-Mz-6ptmBDw3Ezk27ttk:b-jdm173) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L27)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it possible to split up general setup (virtualenv, drake, etc) and per-model testing into separate scripts? e.g.
```
./setup.sh

mkdir -p repos && cd repos
# untar stuff
./format_model_and_generate_manifest.py ... model.sdf
./compare_model_via_drake_and_ingitiom_images.py ...

```
</blockquote></details>

Broke it down into:

```
source setup.sh

bash format_model_and_generate_manifest.sh <model_directory> <model_sdf>

bash compare_model_via_drake_and_ingition_images.sh <model_directory> <model_sdf>
```

I also added a script `setup_transform_test.sh` that calls the three of them to offer a one step command.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 14 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_56uUB9ZRmHHf8MM9:-MzELShf81sCRB8absT0:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For Python styling, could you use `black`?
https://github.com/psf/black
</blockquote></details>

Done.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 117 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5Je_6F27LGjJnvpe:-MyqXPau0cELqE63qq_8:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L117)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you carve this into a separate function?
</blockquote></details>

Done.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 165 at r1](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnkWRP83i9GpCJZqE6t:-MyqXdDk8SdkoMjVEBp1:b-84wk7) ([raw file](https://github.com/ericcousineau-tri/repro/blob/fd357cd63d5569450301c12dabc6183ff6de3cc4/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L165)):*
> g: This should source Gazebo setup file too.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-MzE5Ie35UXfgAatzMJV:b-8am1pp) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yeah, can you carve out all complex instructions / tests into a Python file?
</blockquote></details>

Anything not related to dealing with files and calling scripts is now in Python. With regards to this function, the file generated here is needed to call ignition later, seems like it will be a bit tangled to have it in python, do you think it's still worth to move?


<!-- Sent from Reviewable.io -->

2022-04-04 14:09 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-Mzou2C1-OtNiyH6avkH:b-x8jvtp) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should determine best place for this to land, e..g `drake-ignitino`, `drake-model-interop`, `drake-compatibility`, `drake-comparison`, `drake-benchmarks`.

Once we have some candidates, should post to Drake Slack to solicit other Drake Dev opinions.
</blockquote></details>

Thinking on this some more, I think we can place this inside of `drake-ros`, under `drake_ignition` or something to that effect.
Will confirm w/ Ian.

---


<!-- Sent from Reviewable.io -->

2022-04-07 09:47 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 0 of 8 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 165 at r1](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MnkWRP83i9GpCJZqE6t:-N-0tCqd--gSVHyUCG71:b32wab) ([raw file](https://github.com/ericcousineau-tri/repro/blob/fd357cd63d5569450301c12dabc6183ff6de3cc4/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L165)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

> g: This should source Gazebo setup file too.
</blockquote></details>

\
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-N-2PgOE3Yr6Mg0rF3Bh:biyfgxk) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Yes, we should still move it. Our bash scripts should be as small as possible, and have as little content as possible.
I know Bash and Python pretty well, and I hate programming anything with a modicum of complexity in Bash way more :sweat_smile: 
</blockquote></details>

Shall I try to remove bash completely then? Anything you see we need/want to keep under Bash?


<!-- Sent from Reviewable.io -->

2022-04-10 23:00 UTC, EricCousineau-TRI reviewed
> Reviewed 1 of 6 files at r1, 1 of 3 files at r3, 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 13 of 15 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 5 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_54FI5y-Cn2D6bd04:-N-KflKQ9SIdPS7ynG2R:bnl9g4s) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L5)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

I believe `roslaunch` does tie our hands here.
</blockquote></details>

OK SGTM
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md, line 27 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_60TQ-OrZP9wgg8uu:-N-KfpI71KsiY2YcSqDu:b-w196av) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/README.md#L27)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Broke it down into:

```
source setup.sh

bash format_model_and_generate_manifest.sh <model_directory> <model_sdf>

bash compare_model_via_drake_and_ingition_images.sh <model_directory> <model_sdf>
```

I also added a script `setup_transform_test.sh` that calls the three of them to offer a one step command.
</blockquote></details>

OK Thanks!
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-N-KfuTuET1G2Jp4RoQr:b8jbkh6) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Shall I try to remove bash completely then? Anything you see we need/want to keep under Bash?
</blockquote></details>

This looks better!
If you can minimize it's usage to bare minimum, i.e. only `setup.sh`, which is hopefully max 20-40 lines, then that'd be good.
However, I will mark myself as non-blocking for getting initial revisions in and refining in follow-up passes.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 34 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgFoyCnla9cEA1p_0:-N-KgFoyCnla9cEA1p_1:bplh1e5) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L34)):*
> ```Shell
> 
>     mkdir -p ${_venv_dir}
>     tar -xzf $(_download_drake) -C ${_venv_dir} --strip-components=1
> ```

nit Consider changing this to a `pip` requirement line. For example:
https://github.com/EricCousineau-TRI/repro/blob/34e2c79bbe2989dfa3e1fe6c1a0410e9bf4ec169/drake_stuff/multibody_plant_prototypes/requirements.txt#L1
https://github.com/EricCousineau-TRI/repro/blob/34e2c79bbe2989dfa3e1fe6c1a0410e9bf4ec169/drake_stuff/multibody_plant_prototypes/setup.sh#L31-L35
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 3 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgWej5A1TZ8J5T56N:-N-KgWej5A1TZ8J5T56O:b-lmtcrf) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # Either source this, or use it as a prefix:
> ```

nit Consider removing this docstring. This should ideally only be a script to run, not source.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 12 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgdWl6Vo-d2ujmH9I:-N-KgdWl6Vo-d2ujmH9J:bxifudr) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L12)):*
> ```Shell
> #   ./setup.sh ./my_program
> 
> if [[ $# -lt "2" ]]; then
> ```

nit Should make more strict, `$# -eq 2`; otherwise, unused arguments can be passed.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py, line 63 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KfQbJ2de1QJeahkVo:-N-KfQbJ2de1QJeahkVp:b-1tv0qa) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L63)):*
> ```Python
> 
> 
> def generate_images_and_IoT(simulator, sensor, temp_directory, poses_dir, num_image):
> ```

nit `IoT` =. `IoU` (intersection over union)

Also, consider keeping acronyms as nominal lower case, i.e., `iou`


<!-- Sent from Reviewable.io -->

2022-04-10 23:08 UTC, EricCousineau-TRI requested changes
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 13 of 15 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-N-KisU4-Cl7pCyqMU0K:b-l98ll0) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Thinking on this some more, I think we can place this inside of `drake-ros`, under `drake_ignition` or something to that effect.
Will confirm w/ Ian.
</blockquote></details>

Talked w/ Ian; we could put under `drake-ros`, but ultimately we'd want it to move out.
Instead, I think it'd be good to place in separate repo.
Posted question: https://drakedevelopers.slack.com/archives/C2NN588UA/p1649632043418799

---


<!-- Sent from Reviewable.io -->

2022-04-11 10:24 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 34 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgFoyCnla9cEA1p_0:-N-MOLxH9LJpXJxB7465:b-tu9g62) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L34)):*
> == 1.1.0 
Nicer this way, yes. Done.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 3 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgWej5A1TZ8J5T56N:-N-N6zh28BObQUwYMEzf:bss4a2b) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L3)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider removing this docstring. This should ideally only be a script to run, not source.
</blockquote></details>

Removed.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 12 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgdWl6Vo-d2ujmH9I:-N-N6J4XCrGbTRQz6F2u:bruaopq) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should make more strict, `$# -eq 2`; otherwise, unused arguments can be passed.
</blockquote></details>

Current behavior is with 2 parameters (a directory and a an`sdf` filename) it would trigger the sdf conversion, if only one directory is passed then the entire `unviersal_robot` checkout and conversion happens. I was only trying to preserve the old behavior but it's not 
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py, line 63 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KfQbJ2de1QJeahkVo:-N-N6HKgDFigax0F6-Z0:b-7rl0jd) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L63)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `IoT` =. `IoU` (intersection over union)

Also, consider keeping acronyms as nominal lower case, i.e., `iou`
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-14 20:56 UTC, EricCousineau-TRI requested changes
> Reviewed 8 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 22 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-N-dnZFg4JXz89GTpepE:b-cqk18o) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Talked w/ Ian; we could put under `drake-ros`, but ultimately we'd want it to move out.
Instead, I think it'd be good to place in separate repo.
Posted question: https://drakedevelopers.slack.com/archives/C2NN588UA/p1649632043418799
</blockquote></details>

Per convo on Drake Slack, we will place this in `drake-ros` for now.

Can you create a PR that only has a README placeholder, `setup/install_prereqs` to install necessary deps, along with a new setup for CI?

Then we can start to fold in the work here into that repo.

---
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 115 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dobs0122aLt-EW4cN:-N-dobs0122aLt-EW4cO:b4eh14e) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L115)):*
> ```Python
> # https://github.com/assimp/assimp/issues/849.
> def rotate_ninety_model(scene):
>     rotation = np.matrix([[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]])
> ```

nit For simplicit, consider renaming this to `rotate_root_node(scene, rotation)`, and pass rotation in externally.

Consider denoting rotation as a constant:
```
ROT_X_90 = np.matrix(...)
```
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 206 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dovcV8QhS0zqkcvge:-N-dovcW9LExXFAPR1u6:bf6lbhn) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L206)):*
> ```Python
> 
>     data = etree.tostring(root, pretty_print=True).decode("utf-8")
>     text_file = open(description_file, "w")
> ```

nit Use of `open()` should happen within a `with` block.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 215 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpDAs7OsjEcPTZeoa:-N-dpDAtEPLMGhPBly8A:b-9yadiy) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L215)):*
> ```Python
> # resolved
> def create_pacakge_xml(description_file):
>     if os.path.isfile("package.xml") == False:
> ```

nit Please avoid `if expr == False`. Instead, use `if not expr`.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 221 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dp05eDtKhcUSdUoUE:-N-dp05eDtKhcUSdUoUF:b-ylvaoc) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L221)):*
> ```Python
>         with open("package.xml", "w") as f:
>             f.write(
>                 '<package format="2">\n <name>' + package_name + "</name>\n</package>"
> ```

nit String types mixed between `''` and `""`; can use f-strings.

Consider using `""" """` and f-strings to avoid switching string types.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 231 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpH2p4g7Cl0UZHJCb:-N-dpH2q9SQDZrZL-aNI:b-dnus9u) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L231)):*
> ```Python
> ]
> 
> def preprocess_sdf_and_materials(model_directory, description_file):
> ```

nit Can you be sure to re-apply `black` here?
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 247 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dnuPH8Krm0biftPfz:-N-dnuPIEBuFS7SpzH4X:b-xtxa81) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L247)):*
> ```Python
>       if filename.endswith(".jpg") or filename.endswith(".jpeg"):
>           im = Image.open(os.path.join(root, filename))
>           filename = re.sub('\.jpg|\.jpeg', '.png', filename)
> ```

This (and other strings) needs `r''` to ensure `\.` is escaped correctly.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py, line 329 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpNHb-IQQSC8IiwNq:-N-dpNHb-IQQSC8IiwNr:be4i838) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L329)):*
> ```Python
> if __name__ == "__main__":
>     try:
>         parser = argparse.ArgumentParser()
> ```

nit `try / catch` block encompasses too much code.

Please narrow it down to only surround `main()`.
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh, line 34 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpV491fMoUVafhPtO:-N-dpV491fMoUVafhPtP:b-5cmnh6) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L34)):*
> ```Shell
> 
>     mkdir -p ${_venv_dir}
> #     tar -xzf $(_download_drake) -C ${_venv_dir} --strip-components=1
> ```

nit Can you remove stale comment?
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 12 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgdWl6Vo-d2ujmH9I:-N-do6kX5-qszfCehhiu:b-mwmkjz) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L12)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Current behavior is with 2 parameters (a directory and a an`sdf` filename) it would trigger the sdf conversion, if only one directory is passed then the entire `unviersal_robot` checkout and conversion happens. I was only trying to preserve the old behavior but it's not 
</blockquote></details>

This will fail if `$# -eq 0`. Can you be explicit about this constraint? i.e. `[[ $# -lt 1 || $# -gt 2 ]]`
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh, line 1 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-doFD_BRS2KBWLrtFl:-N-doFDa7r2tN7XLLvxn:b-ms3l93) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L1)):*
> ```Shell
> #!/bin/bash
> ```

nit Scripts should ideally have `set -eu -o pipefail`.

You may briefly need `set +e; ...; set -e` for calling `source setup.sh`
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py, line 72 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dqRXN6KMnZ6Y4xLtv:-N-dqRXN6KMnZ6Y4xLtw:bgvkfkk) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L72)):*
> ```Python
> 
>     color = sensor.color_image_output_port().Eval(sensor_context).data
>     image = Image.frombytes("RGBA", (960, 540), color)
> ```

`(960, 540)` should not be hard-coded here, esp. if it can be determined from `data.`
___
*[drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py, line 72 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dqYRgBN2OKf66Fphj:-N-dqYRgBN2OKf66Fphk:b-5h3p6k) ([raw fil [...]

2022-04-29 12:55 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 18 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-N0pAS9S5ZVjpk5VLX15:baaycbd) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per convo on Drake Slack, we will place this in `drake-ros` for now.

Can you create a PR that only has a README placeholder, `setup/install_prereqs` to install necessary deps, along with a new setup for CI?

Then we can start to fold in the work here into that repo.
</blockquote></details>

Opened a PR with the initial stuff: https://github.com/RobotLocomotion/drake-ros/pull/76. 

If you agree, I will follow up with a PR there with the relevant files from here so we can continue iterating there.

---
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 115 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dobs0122aLt-EW4cN:-N-w0N6H9OZnIj2qLvH4:bs7wumb) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L115)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit For simplicit, consider renaming this to `rotate_root_node(scene, rotation)`, and pass rotation in externally.

Consider denoting rotation as a constant:
```
ROT_X_90 = np.matrix(...)
```
</blockquote></details>

Done.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 206 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dovcV8QhS0zqkcvge:-N-wG_847UlGWlmFcefy:b-yjrv3f) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L206)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Use of `open()` should happen within a `with` block.
</blockquote></details>

True, added.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 215 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpDAs7OsjEcPTZeoa:-N-wI4RM9Ntjf-QH53P_:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L215)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Please avoid `if expr == False`. Instead, use `if not expr`.
</blockquote></details>

Done.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 221 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dp05eDtKhcUSdUoUE:-N-wKAMV9rkDjJRNA6dA:bopg0ky) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L221)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit String types mixed between `''` and `""`; can use f-strings.

Consider using `""" """` and f-strings to avoid switching string types.
</blockquote></details>

Good idea, added also in: https://github.com/marcoag/repro/blob/e2f0b8508490f3febfc63c95d1fd91d6acea696d/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L114.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 231 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpH2p4g7Cl0UZHJCb:-N0-FCGHBmY3GNlcbF4m:bjrehho) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L231)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you be sure to re-apply `black` here?
</blockquote></details>

Yes, I'll make sure I re-apply `black` for each update.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 247 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dnuPH8Krm0biftPfz:-N-wNnaJ9glbzGYPIY-4:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L247)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This (and other strings) needs `r''` to ensure `\.` is escaped correctly.
</blockquote></details>

Done.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py` line 329 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpNHb-IQQSC8IiwNq:-N-wP_pwBwCGdZc8mEJs:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/render_ur_urdfs.py#L329)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit `try / catch` block encompasses too much code.

Please narrow it down to only surround `main()`.
</blockquote></details>

Done.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh` line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-N-wPfoyBwvDDTUW3wDl:bnuz49y) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This looks better!
If you can minimize it's usage to bare minimum, i.e. only `setup.sh`, which is hopefully max 20-40 lines, then that'd be good.
However, I will mark myself as non-blocking for getting initial revisions in and refining in follow-up passes.
</blockquote></details>

Great. I guess we could make the entire thing just python?
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh` line 34 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpV491fMoUVafhPtO:-N-wQ-X3CR_tUNhnBjaA:b-896fix) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L34)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Can you remove stale comment?
</blockquote></details>

Done.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh` line 12 at r6](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-KgdWl6Vo-d2ujmH9I:-N-wQF2W7HfRDLnfUWlZ:b-avub0g) ([raw file](https://github.com/ericcousineau-tri/repro/blob/974bedf8b3ffa3a73814ff2556d5767c2a8db8dc/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This will fail if `$# -eq 0`. Can you be explicit about this constraint? i.e. `[[ $# -lt 1 || $# -gt 2 ]]`
</blockquote></details>

True, will change it. Also in https://github.com/marcoag/repro/blob/e2f0b8508490f3febfc63c95d1fd91d6acea696d/drake_stuff/mbp_robot_arm_joint_limit_stuff/format_model_and_generate_manifest.sh#L35 and https://github.com/marcoag/repro/blob/e2f0b8508490f3febfc63c95d1fd91d6acea696d/drake_stuff/mbp_robot_arm_joint_limit_stuff/compare_model_via_drake_and_ingition_images.sh#L3.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 72 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dqRXN6KMnZ6Y4xLtv:-N-wVQ9tDoMlsRPXZOqS:b-pj07av) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L72)):*
<details><summar [...]

2022-05-03 02:16 UTC, EricCousineau-TRI requested changes
> Reviewed 5 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh` line 29 at r5](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-Mx_5f345IKkcQ6jxnMP:-N16gzs17odIVfC0wrJx:buuw9nu) ([raw file](https://github.com/ericcousineau-tri/repro/blob/ceebe949312fdb2b406de6b93184b7cce120c35f/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup.sh#L29)):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Great. I guess we could make the entire thing just python?
</blockquote></details>

Yup, as much as possible!
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 71 at r8](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N16ggKs0_N3-Y70Zd4l:-N16ggKs0_N3-Y70Zd4m:bbsoukv) ([raw file](https://github.com/ericcousineau-tri/repro/blob/a6b03ff08c3f9eadffd1c9b9806252cc10ba73a7/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L71)):*
> ```Python
>     union_count = 0
>     intersection = 0
>     for i in range(image1.size[0]):
> ```

Per VC, this should be reduced to `intersection_over_union(mask_a, mask_b)`, and `infer_mask(image, bg_pixel=...)`

Additionally, we should avoid large for-loops in pure Python, and instead leverage NumPy for (CPU) acceleration.


<!-- Sent from Reviewable.io -->

2022-05-05 13:16 UTC, marcoag reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 13 of 16 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 90 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dquuv5UfBBXs2PH3Z:-N1JMGrr01VLxvkQ5c9I:bw4emlg) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L90)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't understand why we're checking specific pixel values here.

Can you state in a discussion comment? I believe there should be a better way than this.
</blockquote></details>

Not checking them anymore in b131ace.
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 71 at r8](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N16ggKs0_N3-Y70Zd4l:-N1JM3guBSmad_8QumVy:b70ocbg) ([raw file](https://github.com/ericcousineau-tri/repro/blob/a6b03ff08c3f9eadffd1c9b9806252cc10ba73a7/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L71)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC, this should be reduced to `intersection_over_union(mask_a, mask_b)`, and `infer_mask(image, bg_pixel=...)`

Additionally, we should avoid large for-loops in pure Python, and instead leverage NumPy for (CPU) acceleration.
</blockquote></details>

Done in https://github.com/EricCousineau-TRI/repro/pull/73/commits/b131acea8e7ea0f6f0d3d360c8d6b04ef6d67663.


<!-- Sent from Reviewable.io -->

2022-05-05 14:06 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 140 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpsD-AtGr-h-yk6w7:-N1JXrqm74IptKH374Ky:b-nid0gh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L140)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Same as above - unclear what exactly this value is.
</blockquote></details>

OK Deferring to incorporation into `drake-ros`
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 142 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpuPv9e7LEAivRnQ3:-N1JXs5P5CoDB52ywwi0:b-nid0gh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L142)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Many of these values seem highly coupled to drake rendering.

Can you make those definitions available, and use them here? (width, height, fov, depth, etc.)
</blockquote></details>

OK Deferring to incorporation into `drake-ros`
___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 75 at r9](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N1JTMGdDyzMtOwqC-v_:-N1JXpTE7JcifmiCT9PZ:b-nid0gh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/b131acea8e7ea0f6f0d3d360c8d6b04ef6d67663/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L75)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Soz, one more - consider keeping that as math, and return the value itself.

Then testing can check this at a threshold.
</blockquote></details>

OK Deferring to incorporation into `drake-ros`


<!-- Sent from Reviewable.io -->

2022-05-05 14:07 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI and @marcoag)

___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py` line 135 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-dpm_WBtO9-mdCSRh3:-N1JXtWpAzswxx3itsha:b-nid0gh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/test_models.py#L135)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

We should be more precise than `-3.14`.

Can you either use `degrees="true"`, or use `{math.pi}`?
</blockquote></details>

OK Deferring to incorporation into `drake-ros`


<!-- Sent from Reviewable.io -->

2022-05-05 14:07 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @EricCousineau-TRI)

___
*[`drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh` line 1 at r7](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-N-doFD_BRS2KBWLrtFl:-N1JXufc11-4zh_1kLI-:b-nid0gh) ([raw file](https://github.com/ericcousineau-tri/repro/blob/7d7e74f3468b68baf443b1956d49f318e001a5c5/drake_stuff/mbp_robot_arm_joint_limit_stuff/setup_transform_test.sh#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Scripts should ideally have `set -eu -o pipefail`.

You may briefly need `set +e; ...; set -e` for calling `source setup.sh`
</blockquote></details>

OK Deferring to incorporation into `drake-ros`


<!-- Sent from Reviewable.io -->

2022-05-05 14:07 UTC, EricCousineau-TRI reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>, merging prototype now!

> *[Reviewable](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-:-N1JXzCj6gv_xaagd-wP:b-vyw8h3)* status: 14 of 16 files reviewed, all discussions resolved (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/ericcousineau-tri/repro/73#-MxZwcgW8XNgASfIXVdB:-N1JXw3cBG5oHRuXx6cW:b-uf4cqu) (no related file):*
<details><summary><i>Previously, marcoag (Marco A. Gutiérrez) wrote…</i></summary><blockquote>

Opened a PR with the initial stuff: https://github.com/RobotLocomotion/drake-ros/pull/76. 

If you agree, I will follow up with a PR there with the relevant files from here so we can continue iterating there.
</blockquote></details>

OK Thanks! going to defer more review to the PR train to this repo.

---


<!-- Sent from Reviewable.io -->

2022-05-05 14:08 UTC, merged